language: generic
sudo: required
services: 
  - docker

before_install: 
  - docker build -t jtangs/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true jtangs/react-test npm run test

after_success:
  - docker build -t jntango/multi-client ./client
  - docker build -t jntango/multi-nginx ./nginx
  - docker build -t jntango/multi-server ./server
  - docker build -t jntango/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jntango/multi-client
  - docker push jntango/multi-nginx
  - docker push jntango/multi-server
  - docker push jntango/multi-worker